### ISSUE TITLE
Redirect

### ISSUE THREAD

**Issue by Enes5519** [ayndqy/svelte-micro#10]
Can you implement redirect feature?

**Comment by ayndqy** [comment]
Hi @Enes5519,

There is no need to implement this feature at the package level, because it's easy to do on your own:
```svelte
<script>
  import { router, Route } from 'svelte-micro'
</script>

<Route>
  <Route path="/redirect">{router.push('/redirect-target')}</Route>
</Route>
```

I hope this example will be useful for you.

**Comment by ayndqy** [comment]
I also advise you to pay attention to [this example](https://github.com/ayndqy/svelte-micro/tree/v2#guarded-route) in the documentation. In this case, if the user is not authenticated, they will be redirected.
