### ISSUE TITLE
Route fallback - fatal error

### ISSUE THREAD

**Issue by am35a** [ayndqy/svelte-micro#15]
Route fallback freezing project and stopping browser.
I cannot catch error but http://s4-pi.vercel.app/ as example. If we kill <Route fallback> everything will be alright.

**Comment by ayndqy** [comment]
Thanks for reporting this error.
The issue was reproduced and fixed, the version [v2.5.2](https://github.com/ayndqy/svelte-micro/releases/tag/v2.5.2) contains the bugfix. 
The previous version v2.5.1 was withdrawn as this error introduced in it.
