### ISSUE TITLE
HTTP Error 404 on hot reload of route

### ISSUE THREAD

**Issue by digidub** [ayndqy/svelte-micro#2]
Hi,

When I am viewing a particular route that is not '/' in the browser (e.g. /about, or /contact, or anything else) and I save a change in vscode, the hot reload refreshes the browser window and I receive a `404 error page not found` error.

I'm using svelte version 3 and svelte-micro version 1.

Thanks

**Comment by ayndqy** [comment]
Hi, 
Thank you for your appeal!

Which bundler do you use?
If possible, share how this error can be reproduced.

**Comment by ayndqy** [comment]
Maybe you need to enable SPA mode in dev server settings?
What exactly 404 error do you get? From your app, from bundler or from browser?

**Comment by ayndqy** [comment]
This looks like you did not enable SPA mode in the server settings.
