### ISSUE TITLE
Nested routes trouble

### ISSUE THREAD

**Issue by howesteve** [ayndqy/svelte-micro#5]
Hello,

I love this component and it fits me well. However I'm having an issue routing nested \<Route\> components:

``` js
<Route>
  <Route path="/messages">Messages</Route>
  <Route path="/messages/new">New Message</Route>
</Route>
```
The problem is, when accessing "/messages/new", both routes are being rendered. Is there an "exact path" option?

**Comment by ayndqy** [comment]
Hey @howesteve,

This is proper behavior for this component.
The content inside `<Route path="/messages">` will be rendered on any `/messages` route (such as `/messages/anything`).

To get the behavior you describe you should use a root subroute:
```svelte
<Route>
  <Route path="/messages">
    <Route path="/">Messages</Route>
  </Route>

  <Route path="/messages/new">New Message</Route>
</Route>
```
Now the content inside `<Route path="/">` will be displayed only if path equals to `/messages`.

However, you can simplify your code in this way:
```svelte
<Route>
  <Route path="/messages">
    // The content here will be rendered on any `/messages` route
    <Route path="/">Messages</Route> // This route will be rendered only if path equals to `/messages`
    <Route path="/new">New Message</Route> // This route will be rendered on any `/messages/new` route
  </Route>
</Route>
```

**Comment by howesteve** [comment]
Thanks for your quick response. That worked perfectly.
